/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package androidx.legacy.coreui;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int alpha = 0x7f030027;
        public static final int coordinatorLayoutStyle = 0x7f0300a4;
        public static final int font = 0x7f0300d7;
        public static final int fontProviderAuthority = 0x7f0300d9;
        public static final int fontProviderCerts = 0x7f0300da;
        public static final int fontProviderFetchStrategy = 0x7f0300db;
        public static final int fontProviderFetchTimeout = 0x7f0300dc;
        public static final int fontProviderPackage = 0x7f0300dd;
        public static final int fontProviderQuery = 0x7f0300de;
        public static final int fontStyle = 0x7f0300df;
        public static final int fontVariationSettings = 0x7f0300e0;
        public static final int fontWeight = 0x7f0300e1;
        public static final int keylines = 0x7f03010d;
        public static final int layout_anchor = 0x7f030112;
        public static final int layout_anchorGravity = 0x7f030113;
        public static final int layout_behavior = 0x7f030114;
        public static final int layout_dodgeInsetEdges = 0x7f030140;
        public static final int layout_insetEdge = 0x7f030149;
        public static final int layout_keyline = 0x7f03014a;
        public static final int statusBarBackground = 0x7f0301a6;
        public static final int ttcIndex = 0x7f030208;
    }
    public static final class color {
        private color() {}

        public static final int notification_action_color_filter = 0x7f05006a;
        public static final int notification_icon_bg_color = 0x7f05006b;
        public static final int ripple_material_light = 0x7f050075;
        public static final int secondary_text_default_material_light = 0x7f050077;
    }
    public static final class dimen {
        private dimen() {}

        public static final int compat_button_inset_horizontal_material = 0x7f06004e;
        public static final int compat